/**
 * Per-service pricing — drives the tabbed service pricing block + calculator
 * on /pricing. 16 services × 3 tiers each, plus per-service addons.
 *
 * Pricing calibrated to existing top-of-page tiers (Starter $1,497 / Flagship
 * $9,500 / Retainer $1,997/mo) and SERVICE_CATEGORIES in @/lib/site.
 */

export type ServiceTier = {
  name: "Starter" | "Pro" | "Custom";
  price: number;
  cadence?: "one-time" | "monthly";
  ship: string;
  tagline: string;
  features: string[];
  badge?: "Most picked" | "Best value";
  ctaLabel: string;
  ctaHref: string;
};

export type ServiceAddon = {
  id: string;
  label: string;
  price: number;
  cadence?: "one-time" | "monthly";
};

export type ServicePricing = {
  slug: string;
  label: string;
  category: "Automation" | "AI Content" | "Development" | "Consulting";
  icon: string;
  tagline: string;
  tiers: ServiceTier[];
  addons: ServiceAddon[];
};

const stdAddons: ServiceAddon[] = [
  { id: "rush", label: "Rush 50% (cut ship in half)", price: 750 },
  { id: "revisions", label: "Extra round of revisions", price: 250 },
  { id: "loom-handover", label: "Recorded Loom team handover", price: 250 },
];

export const SERVICE_PRICING: ServicePricing[] = [
  // ── Automation ────────────────────────────────────────────────────────────
  {
    slug: "n8n-automation",
    label: "n8n Automation",
    category: "Automation",
    icon: "Bot",
    tagline: "Self-hosted workflows that replace 3-5 paid SaaS tools.",
    tiers: [
      {
        name: "Starter",
        price: 1497,
        cadence: "one-time",
        ship: "5 days",
        tagline: "One workflow, one trigger, one outcome.",
        features: [
          "1 production workflow (up to 12 nodes)",
          "n8n cloud or self-hosted setup",
          "Error-handling + Slack notifier",
          "Loom walkthrough",
        ],
        ctaLabel: "Start a flow",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 5000,
        cadence: "one-time",
        ship: "10-14 days",
        tagline: "Multi-system pipeline replacing a stack.",
        features: [
          "Up to 3 connected workflows",
          "AI nodes (GPT-4o / Claude) wired in",
          "PostgreSQL log + audit trail",
          "Team SOP + 2 rounds of revisions",
        ],
        badge: "Most picked",
        ctaLabel: "Book Pro build",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 1997,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "Retainer for live ops + iteration.",
        features: [
          "Unlimited small flow tweaks",
          "1 new flow / mo (up to 15 nodes)",
          "Monitoring + alerting",
          "Monthly review call",
        ],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: [
      ...stdAddons,
      { id: "self-host-vps", label: "Self-host on your VPS (setup + harden)", price: 750 },
    ],
  },
  {
    slug: "gohighlevel",
    label: "GoHighLevel CRM",
    category: "Automation",
    icon: "Target",
    tagline: "Full GHL rebuilds — pipelines, funnels, automations.",
    tiers: [
      {
        name: "Starter",
        price: 1497,
        cadence: "one-time",
        ship: "5-7 days",
        tagline: "Account setup + 1 funnel + pipeline.",
        features: [
          "GHL onboarding + brand setup",
          "1 funnel (3-5 steps) + thank-you",
          "5-stage sales pipeline",
          "SMS + email template starter pack",
        ],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 4500,
        cadence: "one-time",
        ship: "10-14 days",
        tagline: "Full ops rebuild — funnels, cadences, automations.",
        features: [
          "Up to 3 funnels + 5 automations",
          "Pipeline forensic + rebuild",
          "Calendly migration + SMS workflows",
          "Loom team SOP",
        ],
        badge: "Most picked",
        ctaLabel: "Book Pro rebuild",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 1497,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "Monthly retainer for live ops.",
        features: [
          "Monthly funnel/automation edits",
          "New campaign + cadence per quarter",
          "Reporting dashboard",
          "Quarterly strategy call",
        ],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
  {
    slug: "zapier-make",
    label: "Zapier & Make",
    category: "Automation",
    icon: "Link",
    tagline: "Multi-tool wiring when n8n is overkill.",
    tiers: [
      {
        name: "Starter",
        price: 997,
        cadence: "one-time",
        ship: "3-5 days",
        tagline: "Single Zap or Make scenario.",
        features: ["1 Zap/scenario (up to 8 steps)", "Error notifier", "Loom walkthrough"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 2997,
        cadence: "one-time",
        ship: "7-10 days",
        tagline: "Suite of connected automations.",
        features: ["Up to 5 connected scenarios", "Shared data store", "2 rounds of revisions"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 997,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "Retainer for unlimited small edits.",
        features: ["Unlimited tweaks", "1 new scenario/mo", "Monitoring"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
  {
    slug: "social-automation",
    label: "Social Automation",
    category: "Automation",
    icon: "Smartphone",
    tagline: "Auto-post + DM responder stack across channels.",
    tiers: [
      {
        name: "Starter",
        price: 1497,
        cadence: "one-time",
        ship: "5-7 days",
        tagline: "Single-channel auto-post + DM bot.",
        features: ["1 channel posting workflow", "DM responder (ManyChat)", "Content calendar template"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 3997,
        cadence: "one-time",
        ship: "10-14 days",
        tagline: "Multi-channel stack with content engine.",
        features: ["3 channels (IG/FB/TikTok/X)", "Cross-channel scheduling", "DM funnel + lead capture", "Loom SOP"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 1497,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "Monthly content + retainer ops.",
        features: ["30 posts/mo across 3 channels", "DM monitoring", "Monthly performance review"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },

  // ── AI Content ────────────────────────────────────────────────────────────
  {
    slug: "ai-video",
    label: "AI Video Creation",
    category: "AI Content",
    icon: "Clapperboard",
    tagline: "Reels, shorts, talking-head at scale.",
    tiers: [
      {
        name: "Starter",
        price: 1297,
        cadence: "one-time",
        ship: "5-7 days",
        tagline: "8 reels from one script batch.",
        features: ["8 vertical reels (9:16)", "Captions + b-roll", "1 voice clone setup"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 4500,
        cadence: "one-time",
        ship: "10-14 days",
        tagline: "30-reel batch + automated pipeline.",
        features: ["30 reels (mixed formats)", "n8n auto-render pipeline", "Posting scheduler"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 1997,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "30 reels/mo on autopilot.",
        features: ["30 reels/mo", "Topic ideation + script", "Captioning + posting"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
  {
    slug: "youtube-automation",
    label: "YouTube Automation",
    category: "AI Content",
    icon: "PlayCircle",
    tagline: "Faceless channel pipeline — script to upload.",
    tiers: [
      {
        name: "Starter",
        price: 1997,
        cadence: "one-time",
        ship: "7-10 days",
        tagline: "Channel setup + 4 long-form videos.",
        features: ["Channel branding + setup", "4 long-form videos (5-8 min)", "Thumbnail templates"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 5997,
        cadence: "one-time",
        ship: "14-21 days",
        tagline: "Full automation pipeline.",
        features: ["Niche + topic research", "12 long-form videos", "n8n auto-publish pipeline", "Analytics dashboard"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 2497,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "8 long-form + 16 shorts /mo.",
        features: ["8 long-form/mo", "16 shorts/mo", "SEO optimization", "Monthly review"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
  {
    slug: "tiktok-automation",
    label: "TikTok Automation",
    category: "AI Content",
    icon: "Music",
    tagline: "Daily content engine that doesn't sound like AI.",
    tiers: [
      {
        name: "Starter",
        price: 1497,
        cadence: "one-time",
        ship: "5-7 days",
        tagline: "15 TikToks + posting setup.",
        features: ["15 vertical videos", "Trend research", "Captions + hashtags"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 3997,
        cadence: "one-time",
        ship: "10-14 days",
        tagline: "60 TikToks + auto-posting.",
        features: ["60 videos in one batch", "Auto-post pipeline", "DM responder", "Trend tracking dashboard"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 1497,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "30 videos/mo on autopilot.",
        features: ["30 videos/mo", "Trend reactivity", "Engagement reporting"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
  {
    slug: "facebook-automation",
    label: "Facebook Automation",
    category: "AI Content",
    icon: "Users",
    tagline: "Page + DM + group reach without burnout.",
    tiers: [
      {
        name: "Starter",
        price: 1297,
        cadence: "one-time",
        ship: "5 days",
        tagline: "Page setup + 10 posts + DM bot.",
        features: ["Page optimization", "10 posts (mixed formats)", "ManyChat DM funnel"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 3497,
        cadence: "one-time",
        ship: "10 days",
        tagline: "Page + groups + ads + automation.",
        features: ["30 posts + 8 reels", "Group engagement bot", "Ad creative starter pack", "Lead capture funnel"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 1297,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "30 posts + DM ops + reporting.",
        features: ["30 posts/mo", "DM monitoring", "Monthly report"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },

  // ── Development ───────────────────────────────────────────────────────────
  {
    slug: "wordpress-seo",
    label: "WordPress SEO Blog",
    category: "Development",
    icon: "Globe",
    tagline: "AEO-tuned content engine that gets cited by Claude/GPT.",
    tiers: [
      {
        name: "Starter",
        price: 1997,
        cadence: "one-time",
        ship: "7 days",
        tagline: "Site rebuild + 10 SEO articles.",
        features: ["WP theme setup or rebuild", "10 long-form articles (1500w+)", "Schema + sitemap + AEO blocks"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 5997,
        cadence: "one-time",
        ship: "10-14 days",
        tagline: "Full engine — 30 posts + automation.",
        features: ["30 AEO-tuned articles", "Auto-publishing pipeline", "Internal linking strategy", "GSC monitoring setup"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 1997,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "10 articles/mo on autopilot.",
        features: ["10 articles/mo (AEO-tuned)", "Keyword research", "Monthly SEO report"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
  {
    slug: "ecommerce-automation",
    label: "E-commerce Automation",
    category: "Development",
    icon: "ShoppingCart",
    tagline: "Shopify + Stripe + n8n stack — abandonment to LTV.",
    tiers: [
      {
        name: "Starter",
        price: 2997,
        cadence: "one-time",
        ship: "7-10 days",
        tagline: "Shopify setup + abandonment recovery.",
        features: ["Theme install + customize", "Abandonment email/SMS automation", "Up to 50 SKU import"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 8500,
        cadence: "one-time",
        ship: "12-14 days",
        tagline: "Full store + post-purchase automation.",
        features: ["Custom Liquid theme", "Klaviyo post-purchase flow", "Up to 200 SKUs", "Returns + courier integration"],
        badge: "Best value",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 2497,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "Store ops + campaigns.",
        features: ["Monthly product launches", "Campaign automation", "Conversion optimization"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
  {
    slug: "vibe-coded-sites",
    label: "Vibe-Coded Websites",
    category: "Development",
    icon: "Zap",
    tagline: "Bespoke Next.js builds — flagship, not template.",
    tiers: [
      {
        name: "Starter",
        price: 2997,
        cadence: "one-time",
        ship: "5-7 days",
        tagline: "5-section landing page, conversion-tuned.",
        features: ["5 bespoke sections", "Mobile-first responsive", "Vercel deploy + analytics"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 9500,
        cadence: "one-time",
        ship: "10-14 days",
        tagline: "Full flagship site (10-14 sections).",
        features: ["10-14 bespoke sections", "SEO + AEO base layer", "CMS or static content", "Conversion funnel wired"],
        badge: "Most picked",
        ctaLabel: "Book Flagship",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 14500,
        cadence: "one-time",
        ship: "14-21 days",
        tagline: "Multi-page enterprise build.",
        features: ["Unlimited sections", "Custom integrations", "GHL/CRM wired", "Stakeholder review rounds"],
        ctaLabel: "Talk scope",
        ctaHref: "/discovery-call",
      },
    ],
    addons: [
      ...stdAddons,
      { id: "blog-engine", label: "Add MDX/CMS blog engine", price: 1500 },
      { id: "i18n", label: "Bilingual / i18n setup", price: 1200 },
    ],
  },
  {
    slug: "ai-chatbots",
    label: "AI Chatbots",
    category: "Development",
    icon: "MessageSquare",
    tagline: "Live chat + web + voice agents that close leads.",
    tiers: [
      {
        name: "Starter",
        price: 1497,
        cadence: "one-time",
        ship: "5 days",
        tagline: "WhatsApp or web chat — single channel.",
        features: ["1 channel deployment", "Knowledge base training (up to 50 pages)", "Lead capture wired"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 4500,
        cadence: "one-time",
        ship: "10 days",
        tagline: "Multi-channel + voice + handoff.",
        features: ["3 channels (web + WA + voice)", "Human handoff routing", "GHL/CRM integration", "Conversation analytics"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 1497,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "Retainer — training + iteration.",
        features: ["Monthly knowledge updates", "Conversation review + tuning", "New intent flows"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },

  // ── Consulting ────────────────────────────────────────────────────────────
  {
    slug: "ai-business-systems",
    label: "AI Business Systems",
    category: "Consulting",
    icon: "Building2",
    tagline: "Operator-grade ops blueprint — strategy + execution.",
    tiers: [
      {
        name: "Starter",
        price: 4997,
        cadence: "one-time",
        ship: "10 days",
        tagline: "Audit + 90-day roadmap + 1 system.",
        features: ["Ops audit (3 sessions)", "90-day automation roadmap", "1 priority system shipped"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 12500,
        cadence: "one-time",
        ship: "21-30 days",
        tagline: "Full transformation — 3 systems + SOPs.",
        features: ["3 priority systems built", "Team SOPs + Loom training", "Stack consolidation plan", "30-day post-launch support"],
        badge: "Best value",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 2997,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "Fractional ops retainer.",
        features: ["2x monthly strategy calls", "Quarterly roadmap", "System iteration + new builds"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
  {
    slug: "strategy-training",
    label: "Strategy & Training",
    category: "Consulting",
    icon: "BookOpen",
    tagline: "Team upskilling + AI playbooks.",
    tiers: [
      {
        name: "Starter",
        price: 997,
        cadence: "one-time",
        ship: "3 days",
        tagline: "90-min team training + playbook.",
        features: ["90-min live workshop", "Custom playbook PDF", "Recorded for replay"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 2997,
        cadence: "one-time",
        ship: "7 days",
        tagline: "Multi-session program + tooling setup.",
        features: ["4 live sessions (90-min)", "Custom prompt library", "Tooling setup for team", "Office hours (2 weeks)"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 1497,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "Fractional AI lead for the team.",
        features: ["Monthly office hours", "Quarterly strategy review", "Playbook updates"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
  {
    slug: "branding-design",
    label: "Branding & Design",
    category: "Consulting",
    icon: "Palette",
    tagline: "Identity + design system that survives scale.",
    tiers: [
      {
        name: "Starter",
        price: 1497,
        cadence: "one-time",
        ship: "5-7 days",
        tagline: "Logo + colors + type + 1-page brand sheet.",
        features: ["Logo (2 directions, 3 revisions)", "Color palette + typography", "1-page brand sheet PDF"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 4997,
        cadence: "one-time",
        ship: "10-14 days",
        tagline: "Full identity system + Figma library.",
        features: ["Full identity system", "Figma component library", "Social templates (10)", "Brand guidelines PDF"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 9500,
        cadence: "one-time",
        ship: "14-21 days",
        tagline: "Enterprise brand + multi-product system.",
        features: ["Multi-product design tokens", "Design system docs site", "Onboarding workshop"],
        ctaLabel: "Talk scope",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
  {
    slug: "ai-content-creation",
    label: "AI Content Creation",
    category: "Consulting",
    icon: "PenTool",
    tagline: "Voice-locked content at volume — AI-tell linted.",
    tiers: [
      {
        name: "Starter",
        price: 1497,
        cadence: "one-time",
        ship: "5 days",
        tagline: "Voice setup + 15-post starter batch.",
        features: ["Voice lock-in workshop", "15 LinkedIn/Twitter posts", "AI-tell linter run"],
        ctaLabel: "Get Starter",
        ctaHref: "/discovery-call",
      },
      {
        name: "Pro",
        price: 4500,
        cadence: "one-time",
        ship: "10-14 days",
        tagline: "Full engine — 50 posts + carousels + automation.",
        features: ["50 posts across formats", "10 carousels (LI/IG)", "Auto-publish pipeline", "Voice-lock prompt library"],
        badge: "Most picked",
        ctaLabel: "Book Pro",
        ctaHref: "/discovery-call",
      },
      {
        name: "Custom",
        price: 1997,
        cadence: "monthly",
        ship: "Ongoing",
        tagline: "Daily voice-locked content across 3 channels.",
        features: ["30 posts/mo", "8 carousels/mo", "Monthly performance review"],
        ctaLabel: "Retainer call",
        ctaHref: "/discovery-call",
      },
    ],
    addons: stdAddons,
  },
];

export const CATEGORIES = [
  "Automation",
  "AI Content",
  "Development",
  "Consulting",
] as const;

export function servicesByCategory(category: (typeof CATEGORIES)[number]) {
  return SERVICE_PRICING.filter((s) => s.category === category);
}

export function findServicePricing(slug: string) {
  return SERVICE_PRICING.find((s) => s.slug === slug);
}
