/**
 * work-builds.ts — single source of truth for the /portfolio grid (WorkShowcase).
 *
 * WORK_BUILDS = the tile data (moved out of WorkShowcase 2026-07-01). Tiles link
 * straight to `liveUrl`; the /work/[slug] detail pages were removed 2026-09-21
 * (301 → /portfolio) and the per-build narrative copy went with them.
 */

export type WorkCategory = "client" | "flagship" | "portal" | "demo";

export type Gig = {
  slug: string;
  title: string;
  client: string;
  niche: string;
  stack: string[];
  outcome: string;
  liveUrl: string;
  category: WorkCategory;
};

export const WORK_BUILDS: Gig[] = [
  // Real client work
  {
    slug: "kitts-recovery-services",
    title: "Kitts Recovery Services",
    client: "Majesta Kitts · EdD MPH CPRS · Rhode Island",
    niche: "Wellness / Peer Recovery",
    stack: ["Custom HTML", "Tailwind", "HeyPeers"],
    outcome:
      "Live peer-led recovery practice. Booking + brand kit shipped in 4 days.",
    liveUrl: "https://www.kittsrecoveryservices.com",
    category: "client",
  },
  {
    slug: "skynetlabs-ariapura-relaunch",
    title: "Ariapura · Sanificazione Condizionatori",
    client: "Italian HVAC client · Bologna",
    niche: "HVAC / Sanitation (IT)",
    stack: ["Next.js", "Tailwind", "Italian SEO"],
    outcome: "Live client relaunch. Multilingual conversion funnel.",
    liveUrl: "https://skynetlabs-ariapura-relaunch.vercel.app",
    category: "client",
  },
  {
    slug: "skynetjoe",
    title: "SkynetLabs · Agency HQ",
    client: "SkynetLabs (in-house · Bali + Lahore)",
    niche: "Agency / Automation",
    stack: ["Next.js 16", "GHL", "n8n"],
    outcome: "Main agency site. AEO-tuned. Pain-first funnel.",
    liveUrl: "https://skynetjoe.com",
    // Not a paying client — it's SkynetLabs' own site. "flagship" is the
    // honest fit: a real, live, self-built showcase (unlike "demo", which
    // implies unshipped/spec work), without the false "Real Client" claim.
    category: "flagship",
  },
  // Flagships
  {
    slug: "skynetlabs-dental-flagship",
    title: "Grand Mercer Dental · Atelier No. 1",
    client: "Bespoke flagship · SoHo, New York",
    niche: "Luxury Healthcare",
    stack: ["Next.js 16", "Tailwind", "Vercel"],
    outcome:
      "$50K-tier flagship. Distilled from niche audit — zero template DNA.",
    liveUrl: "https://skynetlabs-dental-flagship.vercel.app",
    category: "flagship",
  },
  {
    slug: "skynet-flagship-realestate",
    title: "Adrián Vega · Compass Beverly Hills",
    client: "Luxury real estate flagship",
    niche: "Luxury Real Estate",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Serhant-tier bespoke build. Listings + insights + SEO sitemap.",
    liveUrl: "https://skynet-flagship-realestate.vercel.app",
    category: "flagship",
  },
  {
    slug: "auberlin-estate-flagship",
    title: "Auberlin Estate · Hudson Valley Wedding Venue",
    client: "Heritage event venue · Est. 1908",
    niche: "Event Venue / Weddings",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Heritage-brand flagship. Editorial design + booking funnel.",
    liveUrl: "https://auberlin-estate-flagship.vercel.app",
    category: "flagship",
  },
  {
    slug: "restaurant-mu-two",
    title: "Ostería Marquez · Modern Mediterranean Chicago",
    client: "Restaurant flagship",
    niche: "Restaurant / Hospitality",
    stack: ["Next.js", "Tailwind", "Resy"],
    outcome: "Bespoke restaurant build w/ reservations + gallery + IG embed.",
    liveUrl: "https://restaurant-mu-two.vercel.app",
    category: "flagship",
  },
  {
    slug: "skynetlabs-law-demo",
    title: "Harrington Lex LLP · Chicago Trial Boutique",
    client: "Law firm flagship · spec build, no client",
    niche: "Legal / Litigation",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Commercial litigation boutique. SEO sitemap + robots tuned.",
    liveUrl: "https://skynetlabs-law-demo.vercel.app",
    category: "flagship",
  },
  {
    slug: "skynetlabs-medical-demo",
    title: "Riverside Internal Medicine · Concierge Care",
    client: "Concierge healthcare · Chicago · spec build, no client",
    niche: "Concierge Healthcare",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Concierge medicine flagship with patient booking funnel.",
    liveUrl: "https://skynetlabs-medical-demo.vercel.app",
    category: "flagship",
  },
  {
    slug: "skynetlabs-clinic",
    title: "CQC Compliance & Safeguarding Consultancy",
    client: "UK healthcare compliance",
    niche: "Healthcare Compliance (UK)",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "CQC consultancy site. Compliance-grade copy + lead capture.",
    liveUrl: "https://skynetlabs-clinic.vercel.app",
    category: "flagship",
  },
  {
    slug: "skynetlabs-ariapura-cinema",
    title: "Ariapura · Cinema Concept",
    client: "Boutique cinema/villa concept",
    niche: "Hospitality / Cinema",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome:
      "Concept demo for villa-cinema hybrid. Immersive editorial layout.",
    liveUrl: "https://skynetlabs-ariapura-cinema.vercel.app",
    category: "flagship",
  },
  // Niche demos
  {
    slug: "skynetlabs-accountant-demo",
    title: "Sterling & Co CPA · La Jolla Fractional CFO",
    client: "CPA niche demo · CA CPA #134892",
    niche: "Accounting / CFO",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "La Jolla CPA + fractional CFO with trust-stacked credentials.",
    liveUrl: "https://skynetlabs-accountant-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-autorepair-demo",
    title: "Wrench & Co · Portland Euro + Japanese Repair",
    client: "Auto repair niche demo · ASE Master",
    niche: "Auto Repair",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Portland Euro/JDM specialist with 3-yr warranty positioning.",
    liveUrl: "https://skynetlabs-autorepair-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-cleaning-demo",
    title: "Sparkline Residential · Seminole County FL",
    client: "Residential cleaning niche demo",
    niche: "Residential Cleaning",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Trusted-neighbor cleaning service with booking funnel.",
    liveUrl: "https://skynetlabs-cleaning-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-coolcar-demo",
    title: "Cool Car · 3-Variant Spec Demo (DE)",
    client: "German automotive · variant pitch",
    niche: "Automotive / Configurator",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome:
      "Editorial / Cinematic / Brutalist Swiss — 3 directions on one deploy.",
    liveUrl: "https://skynetlabs-coolcar-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-gym-demo",
    title: "Boutique Strength Studio · West Hollywood",
    client: "Gym niche demo · 12-member cohorts",
    niche: "Boutique Fitness",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "WeHo strength studio with cohort-based membership funnel.",
    liveUrl: "https://skynetlabs-gym-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-landscaping-demo",
    title: "Verdant Acre · Seattle Landscape Architecture",
    client: "Landscape architect demo · BSLA",
    niche: "Landscape Architecture",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Editorial portfolio + consultation funnel for high-end design.",
    liveUrl: "https://skynetlabs-landscaping-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-logistics-demo",
    title: "Pacific Lane Logistics · POLB Drayage + Customs",
    client: "Logistics niche demo · SCAC PLLO",
    niche: "Logistics / Drayage",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Port of Long Beach drayage + customs broker positioning.",
    liveUrl: "https://skynetlabs-logistics-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-moving-demo",
    title: "Northbound Moving Co · Boston Binding Quotes",
    client: "Moving niche demo · USDOT 2841902",
    niche: "Moving / Relocation",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Boston mover with binding-quote trust positioning.",
    liveUrl: "https://skynetlabs-moving-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-pestcontrol-demo",
    title: "Sentinel Pest Solutions · Phoenix Scorpion-First",
    client: "Pest control niche demo · entomologist-led",
    niche: "Pest Control",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Phoenix scorpion-specialist with credential stack.",
    liveUrl: "https://skynetlabs-pestcontrol-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-photography-demo",
    title: "Cassidy Renfield Studio · Brooklyn Wedding + Portrait",
    client: "Editorial photographer niche demo",
    niche: "Photography",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Editorial wedding + portrait photographer portfolio + booking.",
    liveUrl: "https://skynetlabs-photography-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-plumbing-demo",
    title: "Cardinal Plumbing · Denver Slab Leak Specialists",
    client: "Plumbing niche demo · Denver CO",
    niche: "Plumbing",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Denver plumber w/ slab leak + tankless specialization funnel.",
    liveUrl: "https://skynetlabs-plumbing-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-roofing-demo",
    title: "Summit Roofing · Charlotte GAF Master Elite",
    client: "Roofing niche demo · NC storm specialists",
    niche: "Roofing",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Charlotte GAF Master Elite roofer w/ storm response positioning.",
    liveUrl: "https://skynetlabs-roofing-demo.vercel.app",
    category: "demo",
  },

  // ── New client work (2026-06 → 2026-07) ──
  {
    slug: "adibug-pest-control",
    title: "Adibug Pest Control · Hampton Roads VA",
    client: "Jerry Omoruyi · Hampton Roads, Virginia",
    niche: "Pest Control",
    stack: ["Next.js 16", "Tailwind", "GHL"],
    outcome:
      "34-page local pest-control build + automation playbook. Shipped in days.",
    liveUrl: "https://adibug-pest-control.vercel.app",
    category: "client",
  },
  {
    slug: "canine-grooming-demo",
    title: "Laurel & Hound · Austin Dog Grooming",
    client: "Boutique grooming + vet-education · Austin TX",
    niche: "Pet Grooming",
    stack: ["Next.js", "Tailwind", "Booking"],
    outcome:
      "Boutique grooming + vet-education site with a booking-ready funnel.",
    liveUrl: "https://canine-grooming-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "lumen-studio-neon",
    title: "Lumen Studio · Content That Earns",
    client: "Content-creation studio",
    niche: "Content / Media",
    stack: ["Next.js 16", "Tailwind", "API routes"],
    outcome: "Dark editorial-luxe content studio with a live contact API.",
    liveUrl: "https://lumen-studio-neon.vercel.app",
    category: "client",
  },
  {
    slug: "denver-nether-commodities",
    title: "Denver Nether Commodities",
    client: "Justin V. · global commodities",
    niche: "Commodities / Finance",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Institutional-tone commodities trading frontend.",
    liveUrl: "https://denver-nether-commodities.vercel.app",
    category: "client",
  },
  {
    slug: "refinado-estudio",
    title: "Refinado Estudio · Identidad Visual",
    client: "Diseñadora premium · Santiago, Chile",
    niche: "Design / Branding (ES)",
    stack: ["Next.js", "Tailwind", "ES SEO"],
    outcome: "Spanish premium brand-identity studio for a Chilean designer.",
    liveUrl: "https://refinado-estudio.vercel.app",
    category: "client",
  },
  {
    slug: "skynetlabs-aesthetic-demo",
    title: "Aesthetic Clinic · 3 Concepts",
    client: "Aesthetic clinic prospect · Germany",
    niche: "MedSpa / Aesthetics",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome:
      "Three working landing concepts on one deploy for a German clinic.",
    liveUrl: "https://skynetlabs-aesthetic-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-wellness-demo",
    title: "Wellness DNA · 5 Premium Landers",
    client: "Functional-wellness brand",
    niche: "Wellness / DNA",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Five premium landing directions for a functional-wellness brand.",
    liveUrl: "https://skynetlabs-wellness-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "gutreno-prelaunch",
    title: "GutReno · Gut, Finally Understood",
    client: "Gut-health prelaunch",
    niche: "Health / Prelaunch",
    stack: ["Next.js", "Tailwind", "Waitlist"],
    outcome: "Prelaunch waitlist funnel for a gut-health brand.",
    liveUrl: "https://gutreno-prelaunch.vercel.app",
    category: "client",
  },
  {
    slug: "next-level-retreat-designs",
    title: "Next Level Retreat · Design Directions",
    client: "Corey Boutwell · retreat brand",
    niche: "Retreat / Wellness",
    stack: ["React", "Vite", "Vercel"],
    outcome: "Six landing directions for a high-ticket retreat brand.",
    liveUrl: "https://next-level-retreat-designs.vercel.app",
    category: "client",
  },
  {
    slug: "rsf-redesign",
    title: "Rockaway's Soul Food Kitchen",
    client: "Soul-food restaurant · online order",
    niche: "Restaurant / Ordering",
    stack: ["Next.js", "Tailwind", "Ordering"],
    outcome: "Soul-food restaurant redesign with an online-order funnel.",
    liveUrl: "https://rsf-redesign.vercel.app",
    category: "client",
  },
  {
    slug: "ksa-shoes-store-five",
    title: "Al-Zaytoun · Premium Arabic Footwear",
    client: "Arabic footwear e-commerce",
    niche: "E-commerce / Retail",
    stack: ["Next.js", "Tailwind", "RTL"],
    outcome: "RTL Arabic premium-footwear storefront.",
    liveUrl: "https://ksa-shoes-store-five.vercel.app",
    category: "client",
  },
  {
    slug: "skynetlabs-inspire-health-pt-demo",
    title: "Inspire Health PT · The Vault",
    client: "Private PT studio · Miami FL",
    niche: "Physical Therapy",
    stack: ["Next.js", "Tailwind", "Intake"],
    outcome: "Private cash-pay PT studio with an intake funnel.",
    liveUrl: "https://skynetlabs-inspire-health-pt-demo.vercel.app",
    category: "demo",
  },

  // ── Portals / apps ──
  {
    slug: "hepatologia-course",
    title: "Programa Cirrosis · Patient Portal",
    client: "Patient-education LMS (ES)",
    niche: "LMS / Healthcare (ES)",
    stack: ["Next.js", "Portal", "ES"],
    outcome: "Spanish patient-education course portal with enrollment.",
    liveUrl: "https://hepatologia-course.vercel.app",
    category: "portal",
  },
  {
    slug: "healthcare-workflow-demo",
    title: "Physician Group Workflow AI",
    client: "Healthcare ops automation",
    niche: "Healthcare / Automation",
    stack: ["Next.js", "n8n", "GHL"],
    outcome: "AI workflow-automation portal concept for physician groups.",
    liveUrl: "https://healthcare-workflow-demo.vercel.app",
    category: "portal",
  },

  // ── New niche demos ──
  {
    slug: "skynetlabs-pizza-demo",
    title: "Forno Vero · Wood-Fired Neapolitan",
    client: "Pizzeria template · cinematic V2",
    niche: "Restaurant",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Cinematic wood-fired pizzeria template.",
    liveUrl: "https://skynetlabs-pizza-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "car-dealer-demo-2026-05-12",
    title: "Atelier Auto Salon",
    client: "Auto dealership demo",
    niche: "Automotive / Dealer",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Curated-inventory dealership with an enquiry funnel.",
    liveUrl: "https://car-dealer-demo-2026-05-12.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-healthcare-demo",
    title: "SkynetLabs Health · Care Navigation",
    client: "Healthcare AI demo",
    niche: "Healthcare / AI",
    stack: ["Next.js", "Tailwind", "AI"],
    outcome: "AI care-navigation concept site.",
    liveUrl: "https://skynetlabs-healthcare-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-medspa-landing",
    title: "Med-Spa · 3 Design Directions",
    client: "MedSpa landing demo",
    niche: "MedSpa",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Three med-spa landing directions on one deploy.",
    liveUrl: "https://skynetlabs-medspa-landing.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-salon-suite-demo",
    title: "Atelier Suites · Salon Suite Rental",
    client: "Salon-suite rental demo",
    niche: "Beauty / Rental",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Salon-suite rental funnel for independent stylists.",
    liveUrl: "https://skynetlabs-salon-suite-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-logo-studio",
    title: "Marque · Logo & Brand Studio",
    client: "Logo / brand studio demo",
    niche: "Design / Branding",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Logo + brand-identity studio landing.",
    liveUrl: "https://skynetlabs-logo-studio.vercel.app",
    category: "demo",
  },
  {
    slug: "photo-portfolio-demos",
    title: "Photography Portfolio · 3 Directions",
    client: "Photographer portfolio demo",
    niche: "Photography",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Three photographer-portfolio directions on one deploy.",
    liveUrl: "https://photo-portfolio-demos.vercel.app",
    category: "demo",
  },
  {
    slug: "wrestling-event-landing",
    title: "Iron Fist Wrestling · Night of Champions",
    client: "Live-event landing demo",
    niche: "Events / Ticketing",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "High-energy live-event ticket landing.",
    liveUrl: "https://wrestling-event-landing.vercel.app",
    category: "demo",
  },
  {
    slug: "wellness-funnel-demo",
    title: "Phoenix Wellness Funnel",
    client: "Wellness funnel demo",
    niche: "Wellness / Funnel",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Conversion-first wellness lead funnel.",
    liveUrl: "https://wellness-funnel-demo.vercel.app",
    category: "demo",
  },
  {
    slug: "skynetlabs-hvac-demo",
    title: "Premier HVAC of Austin",
    client: "HVAC niche demo · Austin TX",
    niche: "HVAC",
    stack: ["Next.js", "Tailwind", "Vercel"],
    outcome: "Austin HVAC service with emergency-call positioning.",
    liveUrl: "https://skynetlabs-hvac-demo.vercel.app",
    category: "demo",
  },
];

export function getBuild(slug: string): Gig | undefined {
  return WORK_BUILDS.find((b) => b.slug === slug);
}
