"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ArrowRight,
  Check,
  Copy,
  Download,
  RotateCcw,
  Sparkles,
} from "lucide-react";
import EmailGate from "@/components/cta/EmailGate";
import ToolUsage from "@/components/tools/ToolUsage";

const STORAGE_KEY = "skynet:ai-agent-spec-writer:v1";

type State = {
  agentName: string;
  role: string;
  tools: string;
  guardrails: string;
  successCriteria: string;
  escalation: string;
};

const INITIAL_STATE: State = {
  agentName: "",
  role: "",
  tools: "",
  guardrails: "",
  successCriteria: "",
  escalation: "",
};

function listify(raw: string): string[] {
  return raw
    .split(/\n+/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function buildSpec(state: State): string {
  const name = state.agentName.trim() || "Untitled Agent";
  const tools = listify(state.tools);
  const guardrails = listify(state.guardrails);
  const success = listify(state.successCriteria);
  const escalation = listify(state.escalation);

  const lines: string[] = [];
  lines.push(`# Agent Spec — ${name}`);
  lines.push("");
  lines.push(
    "> Paste this document to whoever is building or configuring the agent — a developer, an agent framework, or an LLM writing its own system prompt.",
  );
  lines.push("");
  lines.push("## 1. Role");
  lines.push("");
  lines.push(state.role.trim() || "—");
  lines.push("");
  lines.push("## 2. Tools / access");
  lines.push("");
  if (tools.length) {
    tools.forEach((t) => lines.push(`- ${t}`));
  } else {
    lines.push("—");
  }
  lines.push("");
  lines.push("## 3. Guardrails");
  lines.push("");
  if (guardrails.length) {
    guardrails.forEach((g) => lines.push(`- ${g}`));
  } else {
    lines.push("—");
  }
  lines.push("");
  lines.push("## 4. Success criteria");
  lines.push("");
  if (success.length) {
    success.forEach((s) => lines.push(`- ${s}`));
  } else {
    lines.push("—");
  }
  lines.push("");
  lines.push("## 5. Escalation rules");
  lines.push("");
  lines.push(
    "When the agent should stop and hand off to a human instead of proceeding:",
  );
  lines.push("");
  if (escalation.length) {
    escalation.forEach((e) => lines.push(`- ${e}`));
  } else {
    lines.push("—");
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push("## Copy-paste system prompt block");
  lines.push("");
  lines.push("```");
  lines.push(`You are ${name}.`);
  lines.push("");
  lines.push("Role:");
  lines.push(state.role.trim() || "—");
  lines.push("");
  lines.push("You have access to these tools, and only these tools:");
  lines.push(tools.length ? tools.map((t) => `- ${t}`).join("\n") : "—");
  lines.push("");
  lines.push("Hard guardrails — never violate these:");
  lines.push(
    guardrails.length ? guardrails.map((g) => `- ${g}`).join("\n") : "—",
  );
  lines.push("");
  lines.push("You are done successfully when:");
  lines.push(success.length ? success.map((s) => `- ${s}`).join("\n") : "—");
  lines.push("");
  lines.push("Stop and escalate to a human instead of proceeding when:");
  lines.push(
    escalation.length ? escalation.map((e) => `- ${e}`).join("\n") : "—",
  );
  lines.push("```");
  lines.push("");
  lines.push(`_Generated by the SkynetLabs AI Agent Spec Writer._`);
  return lines.join("\n");
}

function isValid(state: State): boolean {
  return (
    state.agentName.trim().length > 0 &&
    state.role.trim().length > 0 &&
    state.successCriteria.trim().length > 0
  );
}

export default function Writer({ calUrl }: { calUrl: string }) {
  const [state, setState] = useState<State>(INITIAL_STATE);
  const [hydrated, setHydrated] = useState(false);
  const [unlocked, setUnlocked] = useState(false);
  const [phase, setPhase] = useState<"build" | "result">("build");
  const [copied, setCopied] = useState(false);
  const resultRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const saved = JSON.parse(raw) as Partial<State>;
        setState({ ...INITIAL_STATE, ...saved });
      }
    } catch {
      // ignore corrupt storage
    }
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated || typeof window === "undefined") return;
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch {
      // ignore
    }
  }, [state, hydrated]);

  const update = useCallback(
    (key: keyof State, val: string) => setState((s) => ({ ...s, [key]: val })),
    [],
  );

  const doc = useMemo(() => buildSpec(state), [state]);
  const valid = isValid(state);

  const onGenerate = () => {
    setPhase("result");
    requestAnimationFrame(() => {
      resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  };

  const onReset = () => {
    if (typeof window !== "undefined") {
      try {
        window.localStorage.removeItem(STORAGE_KEY);
      } catch {
        // ignore
      }
    }
    setState(INITIAL_STATE);
    setPhase("build");
  };

  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(doc);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // ignore
    }
  };

  const onDownload = () => {
    const blob = new Blob([doc], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const safe =
      (state.agentName || "agent-spec")
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "") || "agent-spec";
    a.href = url;
    a.download = `${safe}-spec.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div ref={resultRef}>
      {phase === "build" && (
        <div
          className="rounded-3xl p-6 md:p-8 mb-6"
          style={{
            background: "var(--cream-2)",
            border: "1px solid rgba(26,26,26,0.12)",
            backdropFilter: "blur(14px)",
          }}
        >
          <div className="space-y-5">
            <Field label="Agent name" required>
              <input
                type="text"
                value={state.agentName}
                onChange={(e) => update("agentName", e.target.value)}
                placeholder="e.g. Lead Qualifier Bot"
                className="asw-input"
              />
            </Field>
            <Field
              label="Role"
              required
              hint="What is this agent responsible for, in 2-3 sentences?"
            >
              <textarea
                value={state.role}
                onChange={(e) => update("role", e.target.value)}
                rows={4}
                placeholder="e.g. Reviews every inbound form submission, scores fit against our ICP, and drafts a reply for a human to approve. Never sends anything without approval."
                className="asw-input asw-textarea"
              />
            </Field>
            <Field
              label="Tools / access"
              hint="One per line — APIs, databases, calendars, whatever it can touch."
            >
              <textarea
                value={state.tools}
                onChange={(e) => update("tools", e.target.value)}
                rows={4}
                placeholder={
                  "CRM read/write (contacts, deals)\nCalendar read (availability only)\nEmail draft (no send)"
                }
                className="asw-input asw-textarea"
              />
            </Field>
            <Field
              label="Guardrails"
              hint="One per line — hard rules the agent must never break."
            >
              <textarea
                value={state.guardrails}
                onChange={(e) => update("guardrails", e.target.value)}
                rows={4}
                placeholder={
                  "Never send an email without human approval\nNever discount below list price\nNever discuss pricing with leads scoring under 40"
                }
                className="asw-input asw-textarea"
              />
            </Field>
            <Field
              label="Success criteria"
              required
              hint="One per line — how you know the agent did its job."
            >
              <textarea
                value={state.successCriteria}
                onChange={(e) => update("successCriteria", e.target.value)}
                rows={4}
                placeholder={
                  "Every lead scored within 5 minutes of submission\nDraft reply matches brand voice profile\nNo false-positive high scores on spam"
                }
                className="asw-input asw-textarea"
              />
            </Field>
            <Field
              label="Escalation rules"
              hint="One per line — when it should stop and hand off to a human."
            >
              <textarea
                value={state.escalation}
                onChange={(e) => update("escalation", e.target.value)}
                rows={4}
                placeholder={
                  "Lead mentions a competitor by name\nDeal size over $10k\nAny legal or compliance question"
                }
                className="asw-input asw-textarea"
              />
            </Field>
          </div>

          <div className="flex flex-wrap items-center justify-end gap-3 mt-8">
            <button
              type="button"
              onClick={onGenerate}
              disabled={!valid}
              className="inline-flex items-center gap-2 px-6 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] disabled:opacity-40 disabled:cursor-not-allowed hover:opacity-90 transition"
              style={{ background: "var(--terracotta)" }}
            >
              Generate spec
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
          {!valid && (
            <p className="mt-3 text-xs text-[var(--terracotta-aa)]/90 text-right">
              Agent name, role and success criteria are required.
            </p>
          )}
        </div>
      )}

      {phase === "result" && !unlocked && (
        <EmailGate
          toolSlug="ai-agent-spec-writer"
          toolName="AI Agent Spec Writer"
          promise="your full agent spec document"
          onUnlock={() => setUnlocked(true)}
        />
      )}

      {phase === "result" && unlocked && (
        <div
          className="rounded-3xl p-6 md:p-8 mb-6"
          style={{
            background: "var(--cream-2)",
            border: "1px solid rgba(26,26,26,0.18)",
            backdropFilter: "blur(14px)",
          }}
        >
          <div className="flex items-start justify-between flex-wrap gap-3 mb-5">
            <div>
              <p className="text-xs uppercase tracking-[0.22em] text-[var(--terracotta-aa)] font-semibold mb-2">
                Your Agent Spec
              </p>
              <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight text-[var(--ink)]">
                {state.agentName.trim() || "Untitled Agent"}
              </h2>
            </div>
            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                onClick={onCopy}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink)] border border-[rgba(198,107,63,0.30)] bg-[rgba(198,107,63,0.10)] hover:bg-[rgba(198,107,63,0.85)]/20 transition"
              >
                {copied ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
                {copied ? "Copied" : "Copy doc"}
              </button>
              <button
                type="button"
                onClick={onDownload}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink)] border border-[rgba(26,26,26,0.18)] bg-[var(--cream-2)] hover:bg-[var(--cream-2)] transition"
              >
                <Download className="w-4 h-4" />
                Download .md
              </button>
              <button
                type="button"
                onClick={() => setPhase("build")}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink-2)] border border-[rgba(26,26,26,0.18)] hover:bg-[var(--cream-2)] transition"
              >
                Edit
              </button>
              <button
                type="button"
                onClick={onReset}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink-faint)] hover:text-[var(--terracotta-aa)] transition"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                Reset
              </button>
            </div>
          </div>

          <pre
            className="text-xs sm:text-sm leading-relaxed text-[var(--ink)] overflow-x-auto rounded-2xl p-4 sm:p-5 whitespace-pre-wrap break-words"
            style={{
              background: "var(--cream-3)",
              border: "1px solid rgba(26,26,26,0.12)",
              maxHeight: "60vh",
              overflowY: "auto",
            }}
          >
            {doc}
          </pre>

          <div
            className="mt-6 rounded-2xl p-5 md:p-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-4"
            style={{
              background: "var(--cream-3)",
              border: "1px solid rgba(26,26,26,0.14)",
            }}
          >
            <div>
              <p className="text-xs uppercase tracking-[0.22em] text-[var(--terracotta-aa)] font-semibold mb-1">
                Want this agent actually built?
              </p>
              <p className="text-[var(--ink)] text-base md:text-lg font-semibold">
                I&apos;ll review your spec and scope the build on a free
                30-minute call.
              </p>
            </div>
            <a
              href={calUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] whitespace-nowrap hover:opacity-90 transition"
              style={{ background: "var(--terracotta)" }}
            >
              Book the call
              <ArrowRight className="w-4 h-4" />
            </a>
          </div>

          <p className="mt-4 text-[11px] text-[var(--ink-faint)] inline-flex items-center gap-1.5">
            <Sparkles className="w-3 h-3" />
            Built in your browser from the fields above.
          </p>
        </div>
      )}

      <ToolUsage slug="ai-agent-spec-writer" />

      {/* FEEDBACK */}
      <div className="mt-12 rounded-3xl border border-[rgba(26,26,26,0.12)] bg-[var(--cream-2)] p-6 md:p-8">
        <p className="text-[11px] font-bold uppercase tracking-[0.22em] text-[var(--terracotta-aa)] mb-2">
          — Feedback · 30-second form
        </p>
        <h3 className="text-xl md:text-2xl font-extrabold tracking-tight text-[var(--ink)] mb-2">
          What should this tool do next?
        </h3>
        <p className="text-sm text-[var(--ink-2)] mb-4">
          One missing field, one weird output, one tool you wish existed — tell
          me. I read every reply.
        </p>
        <form action="/api/tool-feedback" method="POST" className="space-y-3">
          <input type="hidden" name="tool" value="ai-agent-spec-writer" />
          <textarea
            name="message"
            required
            rows={3}
            placeholder="What should we improve, fix, or build?"
            className="asw-input asw-textarea"
            style={{
              fontFamily:
                "var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)",
            }}
          />
          <input
            type="email"
            name="email"
            placeholder="Email (optional — only if you want a reply)"
            className="asw-input"
          />
          <button
            type="submit"
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] hover:opacity-90 transition"
            style={{ background: "var(--terracotta)" }}
          >
            Send feedback →
          </button>
        </form>
      </div>

      <style>{`
        .asw-input {
          width: 100%;
          background: var(--cream-3);
          border: 1px solid rgba(26,26,26,0.18);
          border-radius: 12px;
          padding: 0.85rem 1rem;
          color: var(--ink);
          font-size: 0.95rem;
          line-height: 1.5;
          outline: none;
          box-shadow: inset 0 1px 2px rgba(26,26,26,0.04);
          transition: border-color 0.18s ease, box-shadow 0.18s ease, background 0.18s ease;
        }
        .asw-input::placeholder {
          color: var(--ink-faint);
          font-family: var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace);
          font-size: 0.85rem;
        }
        .asw-input:hover { border-color: rgba(26,26,26,0.28); }
        .asw-input:focus {
          border-color: var(--terracotta);
          box-shadow: 0 0 0 3px rgba(198,107,63,0.10), inset 0 1px 2px rgba(26,26,26,0.04);
          background: #ffffff;
        }
        .asw-textarea { resize: vertical; min-height: 80px; font-family: inherit; }
      `}</style>
    </div>
  );
}

function Field({
  label,
  hint,
  required,
  children,
}: {
  label: string;
  hint?: string;
  required?: boolean;
  children: React.ReactNode;
}) {
  return (
    <div>
      <label className="block text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--terracotta-aa)] mb-1.5">
        {label}
        {required ? (
          <span className="text-[var(--terracotta-aa)] ml-1">*</span>
        ) : null}
      </label>
      {children}
      {hint ? (
        <p className="text-xs text-[var(--ink-faint)] mt-1.5">{hint}</p>
      ) : null}
    </div>
  );
}
