"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ArrowRight,
  Check,
  Copy,
  Download,
  GripVertical,
  Plus,
  RotateCcw,
  Sparkles,
  Trash2,
} from "lucide-react";
import EmailGate from "@/components/cta/EmailGate";
import ToolUsage from "@/components/tools/ToolUsage";

const STORAGE_KEY = "skynet:prompt-chain-builder:v1";

type Step = {
  id: string;
  goal: string;
  prompt: string;
  expectedOutput: string;
  passToNext: string;
};

type State = {
  chainName: string;
  steps: Step[];
};

function makeStep(): Step {
  return {
    id: Math.random().toString(36).slice(2, 10),
    goal: "",
    prompt: "",
    expectedOutput: "",
    passToNext: "",
  };
}

const INITIAL_STATE: State = {
  chainName: "",
  steps: [makeStep(), makeStep()],
};

function buildMarkdown(state: State): string {
  const name = state.chainName.trim() || "Untitled Prompt Chain";
  const lines: string[] = [];
  lines.push(`# Prompt Chain — ${name}`);
  lines.push("");
  lines.push(
    '> Run each step in order, in the same conversation. Paste the "pass to next" output from step N as context for step N+1.',
  );
  lines.push("");
  state.steps.forEach((s, i) => {
    lines.push(`## Step ${i + 1}${s.goal ? ` — ${s.goal}` : ""}`);
    lines.push("");
    lines.push(`**Goal:** ${s.goal || "—"}`);
    lines.push("");
    lines.push("**Prompt:**");
    lines.push("```");
    lines.push(s.prompt || "—");
    lines.push("```");
    lines.push("");
    lines.push(`**Expected output:** ${s.expectedOutput || "—"}`);
    lines.push("");
    lines.push(`**Pass to next step:** ${s.passToNext || "—"}`);
    lines.push("");
    if (i < state.steps.length - 1) lines.push("---");
    lines.push("");
  });
  lines.push(`_Generated by the SkynetLabs Prompt Chain Builder._`);
  return lines.join("\n");
}

function buildJson(state: State): string {
  const name = state.chainName.trim() || "Untitled Prompt Chain";
  return JSON.stringify(
    {
      name,
      generatedBy: "SkynetLabs Prompt Chain Builder",
      steps: state.steps.map((s, i) => ({
        step: i + 1,
        goal: s.goal,
        prompt: s.prompt,
        expectedOutput: s.expectedOutput,
        passToNext: s.passToNext,
      })),
    },
    null,
    2,
  );
}

function isValid(state: State): boolean {
  return (
    state.chainName.trim().length > 0 &&
    state.steps.length >= 2 &&
    state.steps.every(
      (s) => s.goal.trim().length > 0 && s.prompt.trim().length > 0,
    )
  );
}

export default function Builder({ calUrl }: { calUrl: string }) {
  const [state, setState] = useState<State>(INITIAL_STATE);
  const [hydrated, setHydrated] = useState(false);
  const [unlocked, setUnlocked] = useState(false);
  const [phase, setPhase] = useState<"build" | "result">("build");
  const [copiedMd, setCopiedMd] = useState(false);
  const [copiedJson, setCopiedJson] = useState(false);
  const resultRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const saved = JSON.parse(raw) as Partial<State>;
        setState({
          chainName: saved.chainName ?? "",
          steps:
            saved.steps && saved.steps.length > 0
              ? saved.steps
              : [makeStep(), makeStep()],
        });
      }
    } catch {
      // ignore corrupt storage
    }
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated || typeof window === "undefined") return;
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch {
      // ignore
    }
  }, [state, hydrated]);

  const updateStep = useCallback(
    (id: string, key: keyof Omit<Step, "id">, val: string) =>
      setState((s) => ({
        ...s,
        steps: s.steps.map((st) => (st.id === id ? { ...st, [key]: val } : st)),
      })),
    [],
  );

  const addStep = useCallback(() => {
    setState((s) => ({ ...s, steps: [...s.steps, makeStep()] }));
  }, []);

  const removeStep = useCallback((id: string) => {
    setState((s) => {
      if (s.steps.length <= 2) return s;
      return { ...s, steps: s.steps.filter((st) => st.id !== id) };
    });
  }, []);

  const markdown = useMemo(() => buildMarkdown(state), [state]);
  const json = useMemo(() => buildJson(state), [state]);
  const valid = isValid(state);

  const onGenerate = () => {
    setPhase("result");
    requestAnimationFrame(() => {
      resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  };

  const onReset = () => {
    if (typeof window !== "undefined") {
      try {
        window.localStorage.removeItem(STORAGE_KEY);
      } catch {
        // ignore
      }
    }
    setState(INITIAL_STATE);
    setPhase("build");
  };

  const copy = async (text: string, which: "md" | "json") => {
    try {
      await navigator.clipboard.writeText(text);
      if (which === "md") {
        setCopiedMd(true);
        setTimeout(() => setCopiedMd(false), 1500);
      } else {
        setCopiedJson(true);
        setTimeout(() => setCopiedJson(false), 1500);
      }
    } catch {
      // ignore
    }
  };

  const download = (text: string, ext: "md" | "json") => {
    const blob = new Blob([text], {
      type: ext === "md" ? "text/markdown" : "application/json",
    });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const safe =
      (state.chainName || "prompt-chain")
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "") || "prompt-chain";
    a.href = url;
    a.download = `${safe}.${ext}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div ref={resultRef}>
      {phase === "build" && (
        <div
          className="rounded-3xl p-6 md:p-8 mb-6"
          style={{
            background: "var(--cream-2)",
            border: "1px solid rgba(26,26,26,0.12)",
            backdropFilter: "blur(14px)",
          }}
        >
          <Field label="Chain name" required>
            <input
              type="text"
              value={state.chainName}
              onChange={(e) =>
                setState((s) => ({ ...s, chainName: e.target.value }))
              }
              placeholder="e.g. Cold email sequence — research → draft → QA"
              className="pcb-input"
            />
          </Field>

          <div className="mt-8 space-y-6">
            {state.steps.map((step, i) => (
              <div
                key={step.id}
                className="rounded-2xl p-5"
                style={{
                  background: "var(--cream-3)",
                  border: "1px solid rgba(26,26,26,0.14)",
                }}
              >
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2">
                    <GripVertical className="w-4 h-4 text-[var(--ink-faint)]" />
                    <span
                      className="inline-flex items-center justify-center rounded-full w-6 h-6 text-xs font-extrabold"
                      style={{
                        background: "var(--terracotta)",
                        color: "var(--cream-3)",
                      }}
                    >
                      {i + 1}
                    </span>
                    <span className="text-sm font-bold text-[var(--ink)] uppercase tracking-wider">
                      Step {i + 1}
                    </span>
                  </div>
                  {state.steps.length > 2 && (
                    <button
                      type="button"
                      onClick={() => removeStep(step.id)}
                      className="inline-flex items-center gap-1.5 text-xs text-[var(--ink-faint)] hover:text-[var(--terracotta-aa)] transition"
                    >
                      <Trash2 className="w-3.5 h-3.5" />
                      Remove
                    </button>
                  )}
                </div>

                <div className="space-y-4">
                  <Field
                    label="Goal"
                    required
                    hint="What should this step accomplish?"
                  >
                    <input
                      type="text"
                      value={step.goal}
                      onChange={(e) =>
                        updateStep(step.id, "goal", e.target.value)
                      }
                      placeholder="e.g. Research the prospect's company and pain points"
                      className="pcb-input"
                    />
                  </Field>
                  <Field label="Prompt" required>
                    <textarea
                      value={step.prompt}
                      onChange={(e) =>
                        updateStep(step.id, "prompt", e.target.value)
                      }
                      rows={4}
                      placeholder="e.g. Given this company URL and industry, list their 3 most likely operational pain points and one line of proof for each."
                      className="pcb-input pcb-textarea"
                    />
                  </Field>
                  <Field
                    label="Expected output"
                    hint="What good output looks like — format, length, tone."
                  >
                    <input
                      type="text"
                      value={step.expectedOutput}
                      onChange={(e) =>
                        updateStep(step.id, "expectedOutput", e.target.value)
                      }
                      placeholder="e.g. 3 bullet points, each under 20 words"
                      className="pcb-input"
                    />
                  </Field>
                  <Field
                    label="Pass to next step"
                    hint="What from this output feeds the next prompt?"
                  >
                    <input
                      type="text"
                      value={step.passToNext}
                      onChange={(e) =>
                        updateStep(step.id, "passToNext", e.target.value)
                      }
                      placeholder="e.g. The 3 pain-point bullets"
                      className="pcb-input"
                    />
                  </Field>
                </div>
              </div>
            ))}
          </div>

          <div className="flex flex-wrap items-center justify-between gap-3 mt-6">
            <button
              type="button"
              onClick={addStep}
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold border border-[rgba(26,26,26,0.18)] text-[var(--ink-2)] hover:bg-[var(--cream-3)] transition"
            >
              <Plus className="w-4 h-4" />
              Add step
            </button>
            <button
              type="button"
              onClick={onGenerate}
              disabled={!valid}
              className="inline-flex items-center gap-2 px-6 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] disabled:opacity-40 disabled:cursor-not-allowed hover:opacity-90 transition"
              style={{ background: "var(--terracotta)" }}
            >
              Generate chain
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
          {!valid && (
            <p className="mt-3 text-xs text-[var(--terracotta-aa)]/90">
              Chain name is required and every step needs a goal + prompt. At
              least 2 steps.
            </p>
          )}
        </div>
      )}

      {phase === "result" && !unlocked && (
        <EmailGate
          toolSlug="prompt-chain-builder"
          toolName="Prompt Chain Builder"
          promise="your exportable prompt chain (markdown + JSON)"
          onUnlock={() => setUnlocked(true)}
        />
      )}

      {phase === "result" && unlocked && (
        <div
          className="rounded-3xl p-6 md:p-8 mb-6"
          style={{
            background: "var(--cream-2)",
            border: "1px solid rgba(26,26,26,0.18)",
            backdropFilter: "blur(14px)",
          }}
        >
          <div className="flex items-start justify-between flex-wrap gap-3 mb-5">
            <div>
              <p className="text-xs uppercase tracking-[0.22em] text-[var(--terracotta-aa)] font-semibold mb-2">
                Your Prompt Chain
              </p>
              <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight text-[var(--ink)]">
                {state.chainName.trim() || "Untitled Prompt Chain"}
              </h2>
            </div>
            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                onClick={() => copy(markdown, "md")}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink)] border border-[rgba(198,107,63,0.30)] bg-[rgba(198,107,63,0.10)] hover:bg-[rgba(198,107,63,0.85)]/20 transition"
              >
                {copiedMd ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
                {copiedMd ? "Copied" : "Copy markdown"}
              </button>
              <button
                type="button"
                onClick={() => download(markdown, "md")}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink)] border border-[rgba(26,26,26,0.18)] bg-[var(--cream-2)] hover:bg-[var(--cream-2)] transition"
              >
                <Download className="w-4 h-4" />
                .md
              </button>
              <button
                type="button"
                onClick={() => download(json, "json")}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink)] border border-[rgba(26,26,26,0.18)] bg-[var(--cream-2)] hover:bg-[var(--cream-2)] transition"
              >
                <Download className="w-4 h-4" />
                .json
              </button>
              <button
                type="button"
                onClick={() => setPhase("build")}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink-2)] border border-[rgba(26,26,26,0.18)] hover:bg-[var(--cream-2)] transition"
              >
                Edit
              </button>
              <button
                type="button"
                onClick={onReset}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink-faint)] hover:text-[var(--terracotta-aa)] transition"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                Reset
              </button>
            </div>
          </div>

          <pre
            className="text-xs sm:text-sm leading-relaxed text-[var(--ink)] overflow-x-auto rounded-2xl p-4 sm:p-5 whitespace-pre-wrap break-words"
            style={{
              background: "var(--cream-3)",
              border: "1px solid rgba(26,26,26,0.12)",
              maxHeight: "60vh",
              overflowY: "auto",
            }}
          >
            {markdown}
          </pre>

          <div
            className="mt-6 rounded-2xl p-5 md:p-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-4"
            style={{
              background: "var(--cream-3)",
              border: "1px solid rgba(26,26,26,0.14)",
            }}
          >
            <div>
              <p className="text-xs uppercase tracking-[0.22em] text-[var(--terracotta-aa)] font-semibold mb-1">
                Want this chain running unattended?
              </p>
              <p className="text-[var(--ink)] text-base md:text-lg font-semibold">
                I&apos;ll wire it into an agent so it runs step-to-step with no
                copy-paste. Free 30-min call.
              </p>
            </div>
            <a
              href={calUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] whitespace-nowrap hover:opacity-90 transition"
              style={{ background: "var(--terracotta)" }}
            >
              Book the call
              <ArrowRight className="w-4 h-4" />
            </a>
          </div>

          <p className="mt-4 text-[11px] text-[var(--ink-faint)] inline-flex items-center gap-1.5">
            <Sparkles className="w-3 h-3" />
            Built in your browser from the steps above.
          </p>
        </div>
      )}

      <ToolUsage slug="prompt-chain-builder" />

      {/* FEEDBACK */}
      <div className="mt-12 rounded-3xl border border-[rgba(26,26,26,0.12)] bg-[var(--cream-2)] p-6 md:p-8">
        <p className="text-[11px] font-bold uppercase tracking-[0.22em] text-[var(--terracotta-aa)] mb-2">
          — Feedback · 30-second form
        </p>
        <h3 className="text-xl md:text-2xl font-extrabold tracking-tight text-[var(--ink)] mb-2">
          What should this tool do next?
        </h3>
        <p className="text-sm text-[var(--ink-2)] mb-4">
          One missing field, one weird output, one tool you wish existed — tell
          me. I read every reply.
        </p>
        <form action="/api/tool-feedback" method="POST" className="space-y-3">
          <input type="hidden" name="tool" value="prompt-chain-builder" />
          <textarea
            name="message"
            required
            rows={3}
            placeholder="What should we improve, fix, or build?"
            className="pcb-input pcb-textarea"
            style={{
              fontFamily:
                "var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)",
            }}
          />
          <input
            type="email"
            name="email"
            placeholder="Email (optional — only if you want a reply)"
            className="pcb-input"
          />
          <button
            type="submit"
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] hover:opacity-90 transition"
            style={{ background: "var(--terracotta)" }}
          >
            Send feedback →
          </button>
        </form>
      </div>

      <style>{`
        .pcb-input {
          width: 100%;
          background: var(--cream-3);
          border: 1px solid rgba(26,26,26,0.18);
          border-radius: 12px;
          padding: 0.85rem 1rem;
          color: var(--ink);
          font-size: 0.95rem;
          line-height: 1.5;
          outline: none;
          box-shadow: inset 0 1px 2px rgba(26,26,26,0.04);
          transition: border-color 0.18s ease, box-shadow 0.18s ease, background 0.18s ease;
        }
        .pcb-input::placeholder {
          color: var(--ink-faint);
          font-family: var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace);
          font-size: 0.85rem;
        }
        .pcb-input:hover { border-color: rgba(26,26,26,0.28); }
        .pcb-input:focus {
          border-color: var(--terracotta);
          box-shadow: 0 0 0 3px rgba(198,107,63,0.10), inset 0 1px 2px rgba(26,26,26,0.04);
          background: #ffffff;
        }
        .pcb-textarea { resize: vertical; min-height: 80px; font-family: inherit; }
      `}</style>
    </div>
  );
}

function Field({
  label,
  hint,
  required,
  children,
}: {
  label: string;
  hint?: string;
  required?: boolean;
  children: React.ReactNode;
}) {
  return (
    <div>
      <label className="block text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--terracotta-aa)] mb-1.5">
        {label}
        {required ? (
          <span className="text-[var(--terracotta-aa)] ml-1">*</span>
        ) : null}
      </label>
      {children}
      {hint ? (
        <p className="text-xs text-[var(--ink-faint)] mt-1.5">{hint}</p>
      ) : null}
    </div>
  );
}
