"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ArrowRight,
  Check,
  Copy,
  Download,
  RotateCcw,
  Sparkles,
} from "lucide-react";
import EmailGate from "@/components/cta/EmailGate";
import ToolUsage from "@/components/tools/ToolUsage";

const STORAGE_KEY = "skynet:system-prompt-generator:v1";

type OutputFormat =
  | "plain-text"
  | "markdown"
  | "json"
  | "bullet-list"
  | "conversational";

const FORMAT_LABEL: Record<OutputFormat, string> = {
  "plain-text": "Plain text",
  markdown: "Markdown",
  json: "JSON",
  "bullet-list": "Bullet list",
  conversational: "Conversational, no formatting",
};

const FORMAT_INSTRUCTION: Record<OutputFormat, string> = {
  "plain-text":
    "Respond in plain prose. No markdown, no headers, no bullet points unless the user explicitly asks for a list.",
  markdown:
    "Respond in clean markdown — use headers, bold and bullet points where they genuinely improve scanability. Never over-format a one-line answer.",
  json: "Respond only with valid JSON matching the structure the user requests. No prose before or after the JSON block unless explicitly asked.",
  "bullet-list":
    "Default to bullet points over paragraphs. Keep each bullet to one idea, under 20 words where possible.",
  conversational:
    "Respond like a knowledgeable colleague in a chat — short paragraphs, no headers, no bullet lists, plain sentences.",
};

type State = {
  role: string;
  constraints: string;
  tone: string;
  outputFormat: OutputFormat;
  extraRules: string;
};

const INITIAL_STATE: State = {
  role: "",
  constraints: "",
  tone: "",
  outputFormat: "plain-text",
  extraRules: "",
};

function listify(raw: string): string[] {
  return raw
    .split(/\n+/)
    .map((s) => s.trim())
    .filter(Boolean);
}

function buildSystemPrompt(state: State): string {
  const role = state.role.trim() || "a helpful assistant";
  const constraints = listify(state.constraints);
  const tone = state.tone.trim();
  const extra = listify(state.extraRules);
  const formatLine = FORMAT_INSTRUCTION[state.outputFormat];

  const lines: string[] = [];
  lines.push(`You are ${role}.`);
  lines.push("");
  if (tone) {
    lines.push(`Tone: ${tone}.`);
    lines.push("");
  }
  lines.push(`Output format: ${formatLine}`);
  if (constraints.length) {
    lines.push("");
    lines.push("Hard constraints — never violate these:");
    constraints.forEach((c) => lines.push(`- ${c}`));
  }
  if (extra.length) {
    lines.push("");
    lines.push("Additional rules:");
    extra.forEach((e) => lines.push(`- ${e}`));
  }
  lines.push("");
  lines.push(
    "If a user request conflicts with any rule above, follow the rule and explain briefly why you can't comply as asked.",
  );
  return lines.join("\n");
}

function buildDoc(state: State): string {
  const role = state.role.trim() || "Untitled Agent/GPT";
  const prompt = buildSystemPrompt(state);
  const lines: string[] = [];
  lines.push(`# System Prompt — ${role}`);
  lines.push("");
  lines.push(
    "> Paste the block below into your custom GPT's instructions, your agent framework's system message, or the first message of a new chat.",
  );
  lines.push("");
  lines.push("## Configuration");
  lines.push("");
  lines.push(`- **Role:** ${state.role.trim() || "—"}`);
  lines.push(`- **Tone:** ${state.tone.trim() || "—"}`);
  lines.push(`- **Output format:** ${FORMAT_LABEL[state.outputFormat]}`);
  lines.push("");
  lines.push("## Copy-paste system prompt");
  lines.push("");
  lines.push("```");
  lines.push(prompt);
  lines.push("```");
  lines.push("");
  lines.push(`_Generated by the SkynetLabs System Prompt Generator._`);
  return lines.join("\n");
}

function isValid(state: State): boolean {
  return state.role.trim().length > 0;
}

export default function Generator({ calUrl }: { calUrl: string }) {
  const [state, setState] = useState<State>(INITIAL_STATE);
  const [hydrated, setHydrated] = useState(false);
  const [unlocked, setUnlocked] = useState(false);
  const [phase, setPhase] = useState<"build" | "result">("build");
  const [copiedPrompt, setCopiedPrompt] = useState(false);
  const [copiedDoc, setCopiedDoc] = useState(false);
  const resultRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const saved = JSON.parse(raw) as Partial<State>;
        setState({ ...INITIAL_STATE, ...saved });
      }
    } catch {
      // ignore corrupt storage
    }
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated || typeof window === "undefined") return;
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch {
      // ignore
    }
  }, [state, hydrated]);

  const update = useCallback(
    <K extends keyof State>(key: K, val: State[K]) =>
      setState((s) => ({ ...s, [key]: val })),
    [],
  );

  const prompt = useMemo(() => buildSystemPrompt(state), [state]);
  const doc = useMemo(() => buildDoc(state), [state]);
  const valid = isValid(state);

  const onGenerate = () => {
    setPhase("result");
    requestAnimationFrame(() => {
      resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  };

  const onReset = () => {
    if (typeof window !== "undefined") {
      try {
        window.localStorage.removeItem(STORAGE_KEY);
      } catch {
        // ignore
      }
    }
    setState(INITIAL_STATE);
    setPhase("build");
  };

  const copy = async (text: string, which: "prompt" | "doc") => {
    try {
      await navigator.clipboard.writeText(text);
      if (which === "prompt") {
        setCopiedPrompt(true);
        setTimeout(() => setCopiedPrompt(false), 1500);
      } else {
        setCopiedDoc(true);
        setTimeout(() => setCopiedDoc(false), 1500);
      }
    } catch {
      // ignore
    }
  };

  const onDownload = () => {
    const blob = new Blob([doc], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const safe =
      (state.role || "system-prompt")
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "") || "system-prompt";
    a.href = url;
    a.download = `${safe}-system-prompt.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div ref={resultRef}>
      {phase === "build" && (
        <div
          className="rounded-3xl p-6 md:p-8 mb-6"
          style={{
            background: "var(--cream-2)",
            border: "1px solid rgba(26,26,26,0.12)",
            backdropFilter: "blur(14px)",
          }}
        >
          <div className="space-y-5">
            <Field
              label="Role"
              required
              hint="What is this GPT/agent, and who is it for?"
            >
              <input
                type="text"
                value={state.role}
                onChange={(e) => update("role", e.target.value)}
                placeholder="e.g. A customer support agent for a SaaS billing product"
                className="spg-input"
              />
            </Field>
            <Field
              label="Constraints"
              hint="One per line — hard rules it must never break."
            >
              <textarea
                value={state.constraints}
                onChange={(e) => update("constraints", e.target.value)}
                rows={4}
                placeholder={
                  'Never issue refunds without confirming the account email\nNever discuss competitor pricing\nNever guess — say "I don\'t know" instead'
                }
                className="spg-input spg-textarea"
              />
            </Field>
            <Field label="Tone" hint="How should it sound?">
              <input
                type="text"
                value={state.tone}
                onChange={(e) => update("tone", e.target.value)}
                placeholder="e.g. Warm, patient, plain English — no corporate jargon"
                className="spg-input"
              />
            </Field>
            <Field label="Output format" required>
              <select
                value={state.outputFormat}
                onChange={(e) =>
                  update("outputFormat", e.target.value as OutputFormat)
                }
                className="spg-input"
              >
                {(Object.keys(FORMAT_LABEL) as OutputFormat[]).map((k) => (
                  <option key={k} value={k}>
                    {FORMAT_LABEL[k]}
                  </option>
                ))}
              </select>
            </Field>
            <Field
              label="Additional rules"
              hint="One per line — anything else it should always or never do."
            >
              <textarea
                value={state.extraRules}
                onChange={(e) => update("extraRules", e.target.value)}
                rows={3}
                placeholder={
                  "Always ask for the order number before troubleshooting\nAlways end with a next-step, never a dead end"
                }
                className="spg-input spg-textarea"
              />
            </Field>
          </div>

          <div className="flex flex-wrap items-center justify-end gap-3 mt-8">
            <button
              type="button"
              onClick={onGenerate}
              disabled={!valid}
              className="inline-flex items-center gap-2 px-6 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] disabled:opacity-40 disabled:cursor-not-allowed hover:opacity-90 transition"
              style={{ background: "var(--terracotta)" }}
            >
              Generate system prompt
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
          {!valid && (
            <p className="mt-3 text-xs text-[var(--terracotta-aa)]/90 text-right">
              Role is required.
            </p>
          )}
        </div>
      )}

      {phase === "result" && !unlocked && (
        <EmailGate
          toolSlug="system-prompt-generator"
          toolName="System Prompt Generator"
          promise="your full system prompt pack (prompt + doc)"
          onUnlock={() => setUnlocked(true)}
        />
      )}

      {phase === "result" && unlocked && (
        <div
          className="rounded-3xl p-6 md:p-8 mb-6"
          style={{
            background: "var(--cream-2)",
            border: "1px solid rgba(26,26,26,0.18)",
            backdropFilter: "blur(14px)",
          }}
        >
          <div className="flex items-start justify-between flex-wrap gap-3 mb-5">
            <div>
              <p className="text-xs uppercase tracking-[0.22em] text-[var(--terracotta-aa)] font-semibold mb-2">
                Your System Prompt
              </p>
              <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight text-[var(--ink)]">
                {state.role.trim() || "Untitled Agent/GPT"}
              </h2>
            </div>
            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                onClick={() => copy(prompt, "prompt")}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink)] border border-[rgba(198,107,63,0.30)] bg-[rgba(198,107,63,0.10)] hover:bg-[rgba(198,107,63,0.85)]/20 transition"
              >
                {copiedPrompt ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
                {copiedPrompt ? "Copied" : "Copy prompt"}
              </button>
              <button
                type="button"
                onClick={onDownload}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink)] border border-[rgba(26,26,26,0.18)] bg-[var(--cream-2)] hover:bg-[var(--cream-2)] transition"
              >
                <Download className="w-4 h-4" />
                Download .md
              </button>
              <button
                type="button"
                onClick={() => setPhase("build")}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink-2)] border border-[rgba(26,26,26,0.18)] hover:bg-[var(--cream-2)] transition"
              >
                Edit
              </button>
              <button
                type="button"
                onClick={onReset}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink-faint)] hover:text-[var(--terracotta-aa)] transition"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                Reset
              </button>
            </div>
          </div>

          <pre
            className="text-xs sm:text-sm leading-relaxed text-[var(--ink)] overflow-x-auto rounded-2xl p-4 sm:p-5 whitespace-pre-wrap break-words"
            style={{
              background: "var(--cream-3)",
              border: "1px solid rgba(26,26,26,0.12)",
              maxHeight: "60vh",
              overflowY: "auto",
            }}
          >
            {prompt}
          </pre>

          <div className="mt-3 flex justify-end">
            <button
              type="button"
              onClick={() => copy(doc, "doc")}
              className="inline-flex items-center gap-1.5 text-xs text-[var(--ink-faint)] hover:text-[var(--terracotta-aa)] transition"
            >
              {copiedDoc ? (
                <Check className="w-3.5 h-3.5" />
              ) : (
                <Copy className="w-3.5 h-3.5" />
              )}
              {copiedDoc
                ? "Copied full doc"
                : "Copy full doc (with config summary)"}
            </button>
          </div>

          <div
            className="mt-6 rounded-2xl p-5 md:p-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-4"
            style={{
              background: "var(--cream-3)",
              border: "1px solid rgba(26,26,26,0.14)",
            }}
          >
            <div>
              <p className="text-xs uppercase tracking-[0.22em] text-[var(--terracotta-aa)] font-semibold mb-1">
                Want this wired into a real agent?
              </p>
              <p className="text-[var(--ink)] text-base md:text-lg font-semibold">
                I&apos;ll take this prompt and build the agent around it on a
                free 30-minute call.
              </p>
            </div>
            <a
              href={calUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] whitespace-nowrap hover:opacity-90 transition"
              style={{ background: "var(--terracotta)" }}
            >
              Book the call
              <ArrowRight className="w-4 h-4" />
            </a>
          </div>

          <p className="mt-4 text-[11px] text-[var(--ink-faint)] inline-flex items-center gap-1.5">
            <Sparkles className="w-3 h-3" />
            Built in your browser from the fields above.
          </p>
        </div>
      )}

      <ToolUsage slug="system-prompt-generator" />

      {/* FEEDBACK */}
      <div className="mt-12 rounded-3xl border border-[rgba(26,26,26,0.12)] bg-[var(--cream-2)] p-6 md:p-8">
        <p className="text-[11px] font-bold uppercase tracking-[0.22em] text-[var(--terracotta-aa)] mb-2">
          — Feedback · 30-second form
        </p>
        <h3 className="text-xl md:text-2xl font-extrabold tracking-tight text-[var(--ink)] mb-2">
          What should this tool do next?
        </h3>
        <p className="text-sm text-[var(--ink-2)] mb-4">
          One missing field, one weird output, one tool you wish existed — tell
          me. I read every reply.
        </p>
        <form action="/api/tool-feedback" method="POST" className="space-y-3">
          <input type="hidden" name="tool" value="system-prompt-generator" />
          <textarea
            name="message"
            required
            rows={3}
            placeholder="What should we improve, fix, or build?"
            className="spg-input spg-textarea"
            style={{
              fontFamily:
                "var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)",
            }}
          />
          <input
            type="email"
            name="email"
            placeholder="Email (optional — only if you want a reply)"
            className="spg-input"
          />
          <button
            type="submit"
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] hover:opacity-90 transition"
            style={{ background: "var(--terracotta)" }}
          >
            Send feedback →
          </button>
        </form>
      </div>

      <style>{`
        .spg-input {
          width: 100%;
          background: var(--cream-3);
          border: 1px solid rgba(26,26,26,0.18);
          border-radius: 12px;
          padding: 0.85rem 1rem;
          color: var(--ink);
          font-size: 0.95rem;
          line-height: 1.5;
          outline: none;
          box-shadow: inset 0 1px 2px rgba(26,26,26,0.04);
          transition: border-color 0.18s ease, box-shadow 0.18s ease, background 0.18s ease;
        }
        .spg-input::placeholder {
          color: var(--ink-faint);
          font-family: var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace);
          font-size: 0.85rem;
        }
        .spg-input:hover { border-color: rgba(26,26,26,0.28); }
        .spg-input:focus {
          border-color: var(--terracotta);
          box-shadow: 0 0 0 3px rgba(198,107,63,0.10), inset 0 1px 2px rgba(26,26,26,0.04);
          background: #ffffff;
        }
        .spg-textarea { resize: vertical; min-height: 80px; font-family: inherit; }
        select.spg-input {
          appearance: none;
          -webkit-appearance: none;
          background-image: url("data:image/svg+xml;charset=UTF-8,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='none' stroke='%23C66B3F' stroke-width='2.5' stroke-linecap='round' stroke-linejoin='round'%3e%3cpolyline points='6 9 12 15 18 9'/%3e%3c/svg%3e");
          background-repeat: no-repeat;
          background-position: right 0.9rem center;
          background-size: 14px;
          padding-right: 2.5rem;
        }
      `}</style>
    </div>
  );
}

function Field({
  label,
  hint,
  required,
  children,
}: {
  label: string;
  hint?: string;
  required?: boolean;
  children: React.ReactNode;
}) {
  return (
    <div>
      <label className="block text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--terracotta-aa)] mb-1.5">
        {label}
        {required ? (
          <span className="text-[var(--terracotta-aa)] ml-1">*</span>
        ) : null}
      </label>
      {children}
      {hint ? (
        <p className="text-xs text-[var(--ink-faint)] mt-1.5">{hint}</p>
      ) : null}
    </div>
  );
}
