"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  ArrowRight,
  Bot,
  Check,
  Copy,
  Download,
  Plus,
  RotateCcw,
  Sparkles,
  Trash2,
  User,
} from "lucide-react";
import EmailGate from "@/components/cta/EmailGate";
import ToolUsage from "@/components/tools/ToolUsage";

const STORAGE_KEY = "skynet:ai-sop-generator:v1";

type StepItem = {
  id: string;
  text: string;
  automationCandidate: boolean;
};

type State = {
  processName: string;
  owner: string;
  steps: StepItem[];
};

function makeStep(): StepItem {
  return {
    id: Math.random().toString(36).slice(2, 10),
    text: "",
    automationCandidate: false,
  };
}

const INITIAL_STATE: State = {
  processName: "",
  owner: "",
  steps: [makeStep(), makeStep(), makeStep()],
};

function buildSop(state: State): string {
  const name = state.processName.trim() || "Untitled Process";
  const owner = state.owner.trim() || "—";
  const steps = state.steps.filter((s) => s.text.trim().length > 0);
  const automationCount = steps.filter((s) => s.automationCandidate).length;

  const lines: string[] = [];
  lines.push(`# SOP — ${name}`);
  lines.push("");
  lines.push(`**Process owner:** ${owner}`);
  lines.push(
    `**Steps:** ${steps.length} · **Automation candidates:** ${automationCount}`,
  );
  lines.push("");
  lines.push("---");
  lines.push("");
  steps.forEach((s, i) => {
    const flag = s.automationCandidate ? " 🤖 AUTOMATION CANDIDATE" : "";
    lines.push(`### Step ${i + 1}${flag}`);
    lines.push("");
    lines.push(s.text.trim() || "—");
    if (s.automationCandidate) {
      lines.push("");
      lines.push(
        "> This step is repetitive, rule-based or high-volume — a strong candidate for an n8n workflow, Zapier, or an AI agent instead of manual work.",
      );
    }
    lines.push("");
  });
  lines.push("---");
  lines.push("");
  lines.push("## Automation summary");
  lines.push("");
  if (automationCount > 0) {
    lines.push(
      `${automationCount} of ${steps.length} step(s) flagged as automation candidates:`,
    );
    lines.push("");
    steps
      .filter((s) => s.automationCandidate)
      .forEach((s, i) => lines.push(`${i + 1}. ${s.text.trim()}`));
  } else {
    lines.push("No steps flagged as automation candidates yet.");
  }
  lines.push("");
  lines.push(`_Generated by the SkynetLabs AI SOP Generator._`);
  return lines.join("\n");
}

function isValid(state: State): boolean {
  return (
    state.processName.trim().length > 0 &&
    state.steps.filter((s) => s.text.trim().length > 0).length >= 2
  );
}

export default function Generator({ calUrl }: { calUrl: string }) {
  const [state, setState] = useState<State>(INITIAL_STATE);
  const [hydrated, setHydrated] = useState(false);
  const [unlocked, setUnlocked] = useState(false);
  const [phase, setPhase] = useState<"build" | "result">("build");
  const [copied, setCopied] = useState(false);
  const resultRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (typeof window === "undefined") return;
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY);
      if (raw) {
        const saved = JSON.parse(raw) as Partial<State>;
        setState({
          processName: saved.processName ?? "",
          owner: saved.owner ?? "",
          steps:
            saved.steps && saved.steps.length > 0
              ? saved.steps
              : [makeStep(), makeStep(), makeStep()],
        });
      }
    } catch {
      // ignore corrupt storage
    }
    setHydrated(true);
  }, []);

  useEffect(() => {
    if (!hydrated || typeof window === "undefined") return;
    try {
      window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
    } catch {
      // ignore
    }
  }, [state, hydrated]);

  const updateStep = useCallback(
    (id: string, key: keyof Omit<StepItem, "id">, val: string | boolean) =>
      setState((s) => ({
        ...s,
        steps: s.steps.map((st) => (st.id === id ? { ...st, [key]: val } : st)),
      })),
    [],
  );

  const addStep = useCallback(() => {
    setState((s) => ({ ...s, steps: [...s.steps, makeStep()] }));
  }, []);

  const removeStep = useCallback((id: string) => {
    setState((s) => {
      if (s.steps.length <= 2) return s;
      return { ...s, steps: s.steps.filter((st) => st.id !== id) };
    });
  }, []);

  const doc = useMemo(() => buildSop(state), [state]);
  const valid = isValid(state);

  const onGenerate = () => {
    setPhase("result");
    requestAnimationFrame(() => {
      resultRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });
    });
  };

  const onReset = () => {
    if (typeof window !== "undefined") {
      try {
        window.localStorage.removeItem(STORAGE_KEY);
      } catch {
        // ignore
      }
    }
    setState(INITIAL_STATE);
    setPhase("build");
  };

  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(doc);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // ignore
    }
  };

  const onDownload = () => {
    const blob = new Blob([doc], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const safe =
      (state.processName || "sop")
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, "-")
        .replace(/(^-|-$)/g, "") || "sop";
    a.href = url;
    a.download = `${safe}-sop.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div ref={resultRef}>
      {phase === "build" && (
        <div
          className="rounded-3xl p-6 md:p-8 mb-6"
          style={{
            background: "var(--cream-2)",
            border: "1px solid rgba(26,26,26,0.12)",
            backdropFilter: "blur(14px)",
          }}
        >
          <div className="grid sm:grid-cols-2 gap-5 mb-6">
            <Field label="Process name" required>
              <input
                type="text"
                value={state.processName}
                onChange={(e) =>
                  setState((s) => ({ ...s, processName: e.target.value }))
                }
                placeholder="e.g. New client onboarding"
                className="sop-input"
              />
            </Field>
            <Field label="Process owner" hint="Who's accountable for this SOP?">
              <input
                type="text"
                value={state.owner}
                onChange={(e) =>
                  setState((s) => ({ ...s, owner: e.target.value }))
                }
                placeholder="e.g. Ops manager"
                className="sop-input"
              />
            </Field>
          </div>

          <div className="space-y-4">
            {state.steps.map((step, i) => (
              <div
                key={step.id}
                className="rounded-2xl p-4"
                style={{
                  background: "var(--cream-3)",
                  border: step.automationCandidate
                    ? "1px solid rgba(198,107,63,0.45)"
                    : "1px solid rgba(26,26,26,0.14)",
                }}
              >
                <div className="flex items-start gap-3">
                  <span
                    className="inline-flex items-center justify-center rounded-full w-6 h-6 text-xs font-extrabold flex-shrink-0 mt-1"
                    style={{
                      background: "var(--terracotta)",
                      color: "var(--cream-3)",
                    }}
                  >
                    {i + 1}
                  </span>
                  <div className="flex-1 min-w-0">
                    <textarea
                      value={step.text}
                      onChange={(e) =>
                        updateStep(step.id, "text", e.target.value)
                      }
                      rows={2}
                      placeholder={`e.g. ${
                        i === 0
                          ? "Send welcome email with intake form link"
                          : i === 1
                            ? "Manually copy intake responses into CRM"
                            : "Schedule kickoff call within 48 hours"
                      }`}
                      className="sop-input sop-textarea"
                    />
                    <label className="mt-2 inline-flex items-center gap-2 text-xs font-semibold cursor-pointer select-none">
                      <input
                        type="checkbox"
                        checked={step.automationCandidate}
                        onChange={(e) =>
                          updateStep(
                            step.id,
                            "automationCandidate",
                            e.target.checked,
                          )
                        }
                        className="w-4 h-4"
                        style={{ accentColor: "var(--terracotta)" }}
                      />
                      <span
                        className="inline-flex items-center gap-1"
                        style={{
                          color: step.automationCandidate
                            ? "var(--terracotta-aa)"
                            : "var(--ink-faint)",
                        }}
                      >
                        {step.automationCandidate ? (
                          <Bot className="w-3.5 h-3.5" />
                        ) : (
                          <User className="w-3.5 h-3.5" />
                        )}
                        Automation candidate
                      </span>
                    </label>
                  </div>
                  {state.steps.length > 2 && (
                    <button
                      type="button"
                      onClick={() => removeStep(step.id)}
                      className="text-[var(--ink-faint)] hover:text-[var(--terracotta-aa)] transition flex-shrink-0"
                      aria-label="Remove step"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>

          <div className="flex flex-wrap items-center justify-between gap-3 mt-6">
            <button
              type="button"
              onClick={addStep}
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold border border-[rgba(26,26,26,0.18)] text-[var(--ink-2)] hover:bg-[var(--cream-3)] transition"
            >
              <Plus className="w-4 h-4" />
              Add step
            </button>
            <button
              type="button"
              onClick={onGenerate}
              disabled={!valid}
              className="inline-flex items-center gap-2 px-6 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] disabled:opacity-40 disabled:cursor-not-allowed hover:opacity-90 transition"
              style={{ background: "var(--terracotta)" }}
            >
              Generate SOP
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
          {!valid && (
            <p className="mt-3 text-xs text-[var(--terracotta-aa)]/90">
              Process name is required, plus at least 2 filled-in steps.
            </p>
          )}
        </div>
      )}

      {phase === "result" && !unlocked && (
        <EmailGate
          toolSlug="ai-sop-generator"
          toolName="AI SOP Generator"
          promise="your full formatted SOP document"
          onUnlock={() => setUnlocked(true)}
        />
      )}

      {phase === "result" && unlocked && (
        <div
          className="rounded-3xl p-6 md:p-8 mb-6"
          style={{
            background: "var(--cream-2)",
            border: "1px solid rgba(26,26,26,0.18)",
            backdropFilter: "blur(14px)",
          }}
        >
          <div className="flex items-start justify-between flex-wrap gap-3 mb-5">
            <div>
              <p className="text-xs uppercase tracking-[0.22em] text-[var(--terracotta-aa)] font-semibold mb-2">
                Your SOP
              </p>
              <h2 className="text-2xl md:text-3xl font-extrabold tracking-tight text-[var(--ink)]">
                {state.processName.trim() || "Untitled Process"}
              </h2>
            </div>
            <div className="flex flex-wrap gap-2">
              <button
                type="button"
                onClick={onCopy}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink)] border border-[rgba(198,107,63,0.30)] bg-[rgba(198,107,63,0.10)] hover:bg-[rgba(198,107,63,0.85)]/20 transition"
              >
                {copied ? (
                  <Check className="w-4 h-4" />
                ) : (
                  <Copy className="w-4 h-4" />
                )}
                {copied ? "Copied" : "Copy doc"}
              </button>
              <button
                type="button"
                onClick={onDownload}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink)] border border-[rgba(26,26,26,0.18)] bg-[var(--cream-2)] hover:bg-[var(--cream-2)] transition"
              >
                <Download className="w-4 h-4" />
                Download .md
              </button>
              <button
                type="button"
                onClick={() => setPhase("build")}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink-2)] border border-[rgba(26,26,26,0.18)] hover:bg-[var(--cream-2)] transition"
              >
                Edit
              </button>
              <button
                type="button"
                onClick={onReset}
                className="inline-flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold text-[var(--ink-faint)] hover:text-[var(--terracotta-aa)] transition"
              >
                <RotateCcw className="w-3.5 h-3.5" />
                Reset
              </button>
            </div>
          </div>

          <pre
            className="text-xs sm:text-sm leading-relaxed text-[var(--ink)] overflow-x-auto rounded-2xl p-4 sm:p-5 whitespace-pre-wrap break-words"
            style={{
              background: "var(--cream-3)",
              border: "1px solid rgba(26,26,26,0.12)",
              maxHeight: "60vh",
              overflowY: "auto",
            }}
          >
            {doc}
          </pre>

          <div
            className="mt-6 rounded-2xl p-5 md:p-6 flex flex-col md:flex-row items-start md:items-center justify-between gap-4"
            style={{
              background: "var(--cream-3)",
              border: "1px solid rgba(26,26,26,0.14)",
            }}
          >
            <div>
              <p className="text-xs uppercase tracking-[0.22em] text-[var(--terracotta-aa)] font-semibold mb-1">
                Want the flagged steps actually automated?
              </p>
              <p className="text-[var(--ink)] text-base md:text-lg font-semibold">
                I&apos;ll review your SOP and scope which steps to wire first.
                Free 30-min call.
              </p>
            </div>
            <a
              href={calUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] whitespace-nowrap hover:opacity-90 transition"
              style={{ background: "var(--terracotta)" }}
            >
              Book the call
              <ArrowRight className="w-4 h-4" />
            </a>
          </div>

          <p className="mt-4 text-[11px] text-[var(--ink-faint)] inline-flex items-center gap-1.5">
            <Sparkles className="w-3 h-3" />
            Built in your browser from the steps above.
          </p>
        </div>
      )}

      <ToolUsage slug="ai-sop-generator" />

      {/* FEEDBACK */}
      <div className="mt-12 rounded-3xl border border-[rgba(26,26,26,0.12)] bg-[var(--cream-2)] p-6 md:p-8">
        <p className="text-[11px] font-bold uppercase tracking-[0.22em] text-[var(--terracotta-aa)] mb-2">
          — Feedback · 30-second form
        </p>
        <h3 className="text-xl md:text-2xl font-extrabold tracking-tight text-[var(--ink)] mb-2">
          What should this tool do next?
        </h3>
        <p className="text-sm text-[var(--ink-2)] mb-4">
          One missing field, one weird output, one tool you wish existed — tell
          me. I read every reply.
        </p>
        <form action="/api/tool-feedback" method="POST" className="space-y-3">
          <input type="hidden" name="tool" value="ai-sop-generator" />
          <textarea
            name="message"
            required
            rows={3}
            placeholder="What should we improve, fix, or build?"
            className="sop-input sop-textarea"
            style={{
              fontFamily:
                "var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace)",
            }}
          />
          <input
            type="email"
            name="email"
            placeholder="Email (optional — only if you want a reply)"
            className="sop-input"
          />
          <button
            type="submit"
            className="inline-flex items-center gap-2 px-5 py-2.5 rounded-lg font-semibold text-[var(--cream-3)] hover:opacity-90 transition"
            style={{ background: "var(--terracotta)" }}
          >
            Send feedback →
          </button>
        </form>
      </div>

      <style>{`
        .sop-input {
          width: 100%;
          background: var(--cream-3);
          border: 1px solid rgba(26,26,26,0.18);
          border-radius: 12px;
          padding: 0.85rem 1rem;
          color: var(--ink);
          font-size: 0.95rem;
          line-height: 1.5;
          outline: none;
          box-shadow: inset 0 1px 2px rgba(26,26,26,0.04);
          transition: border-color 0.18s ease, box-shadow 0.18s ease, background 0.18s ease;
        }
        .sop-input::placeholder {
          color: var(--ink-faint);
          font-family: var(--font-mono, ui-monospace, SFMono-Regular, Menlo, monospace);
          font-size: 0.85rem;
        }
        .sop-input:hover { border-color: rgba(26,26,26,0.28); }
        .sop-input:focus {
          border-color: var(--terracotta);
          box-shadow: 0 0 0 3px rgba(198,107,63,0.10), inset 0 1px 2px rgba(26,26,26,0.04);
          background: #ffffff;
        }
        .sop-textarea { resize: vertical; min-height: 56px; font-family: inherit; }
      `}</style>
    </div>
  );
}

function Field({
  label,
  hint,
  required,
  children,
}: {
  label: string;
  hint?: string;
  required?: boolean;
  children: React.ReactNode;
}) {
  return (
    <div>
      <label className="block text-[11px] font-bold uppercase tracking-[0.18em] text-[var(--terracotta-aa)] mb-1.5">
        {label}
        {required ? (
          <span className="text-[var(--terracotta-aa)] ml-1">*</span>
        ) : null}
      </label>
      {children}
      {hint ? (
        <p className="text-xs text-[var(--ink-faint)] mt-1.5">{hint}</p>
      ) : null}
    </div>
  );
}
